arb-dir: lib/l10n
template-arb-file: app_fr.arb
output-localization-file: l10n.dart
output-class: AppLocalizations
nullable-getter: false
untranslated-messages-file: build/l10n_missing.txt
use-escaping: true

