import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';

import 'DS.dart';

class AppTheme {
  static ThemeData theme = ThemeData(
    applyElevationOverlayColor: null,
    cupertinoOverrideTheme: null,
    extensions: null,
    inputDecorationTheme: InputDecorationTheme(
      errorMaxLines: AppInputDecorationTheme.errorMaxLines,
      iconColor: AppInputDecorationTheme.iconColor,
      prefixIconColor: AppInputDecorationTheme.prefixIconColor,
      suffixIconColor: AppInputDecorationTheme.suffixIconColor,
      filled: AppInputDecorationTheme.filled,
      fillColor: AppInputDecorationTheme.fillColor,
      floatingLabelAlignment: AppInputDecorationTheme.floatingLabelAlignment,
      floatingLabelBehavior: AppInputDecorationTheme.floatingLabelBehavior,
      enabledBorder: AppInputDecorationTheme.enabledBorder,
      focusedBorder: AppInputDecorationTheme.focusedBorder,
      disabledBorder: AppInputDecorationTheme.disabledBorder,
      errorBorder: AppInputDecorationTheme.errorBorder,
      outlineBorder: AppInputDecorationTheme.outlineBorder,
      focusColor: AppInputDecorationTheme.focusColor,
      hoverColor: AppInputDecorationTheme.hoverColor,
      border: AppInputDecorationTheme.border,
      contentPadding: AppInputDecorationTheme.contentPadding,
      isDense: AppInputDecorationTheme.isDense,
      labelStyle: AppInputDecorationTheme.labelStyle,
      floatingLabelStyle: AppInputDecorationTheme.floatingLabelStyle,
      helperStyle: AppInputDecorationTheme.helperStyle,
      helperMaxLines: AppInputDecorationTheme.helperMaxLines,
      hintStyle: AppInputDecorationTheme.hintStyle,
      errorStyle: AppInputDecorationTheme.errorStyle,
      isCollapsed: AppInputDecorationTheme.isCollapsed,
      prefixStyle: AppInputDecorationTheme.prefixStyle,
      suffixStyle: AppInputDecorationTheme.suffixStyle,
      counterStyle: AppInputDecorationTheme.counterStyle,
      activeIndicatorBorder: AppInputDecorationTheme.activeIndicatorBorder,
      focusedErrorBorder: AppInputDecorationTheme.focusedErrorBorder,
      alignLabelWithHint: AppInputDecorationTheme.alignLabelWithHint,
      // constraints: AppInputDecorationTheme.constraints,
    ),
    materialTapTargetSize: null,
    pageTransitionsTheme: null,
    platform: null,
    scrollbarTheme: ScrollbarThemeData(
      thumbVisibility: AppScrollbarThemeData.thumbVisibility,
      thickness: AppScrollbarThemeData.thickness,
      trackVisibility: AppScrollbarThemeData.trackVisibility,
      radius: AppScrollbarThemeData.radius,
      thumbColor: AppScrollbarThemeData.thumbColor,
      trackColor: AppScrollbarThemeData.trackColor,
      trackBorderColor: AppScrollbarThemeData.trackBorderColor,
      crossAxisMargin: AppScrollbarThemeData.crossAxisMargin,
      mainAxisMargin: AppScrollbarThemeData.mainAxisMargin,
      minThumbLength: AppScrollbarThemeData.minThumbLength,
      interactive: AppScrollbarThemeData.interactive,
    ),
    splashFactory: null,
    useMaterial3: true,
    visualDensity: VisualDensity.compact,
    brightness: Brightness.light,
    canvasColor: AppColors.whiteSwatch,
    cardColor: null,
    colorScheme: ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.whiteSwatch,
      onPrimary: AppColors.secondary.shade900,
      primaryContainer: AppColors.primary,
      onPrimaryContainer: AppColors.whiteSwatch,
      secondary: AppColors.whiteSwatch,
      onSecondary: AppColors.primary,
      secondaryContainer: AppColors.secondaryDefault,
      onSecondaryContainer: AppColors.whiteSwatch,
      tertiary: null,
      onTertiary: null,
      tertiaryContainer: null,
      onTertiaryContainer: null,
      error: AppColors.errorDefault,
      onError: AppColors.whiteSwatch,
      errorContainer: AppColors.errorDefault,
      onErrorContainer: AppColors.whiteSwatch,
      surface: AppColors.whiteSwatch,
      onSurface: AppColors.textPrimary,
      onSurfaceVariant: null,
      outline: null,
      outlineVariant: null,
      shadow: AppColors.primaryDefault,
      scrim: null,
      inverseSurface: null,
      onInverseSurface: null,
      inversePrimary: null,
      surfaceTint: null,
    ),
    colorSchemeSeed: null,
    disabledColor: AppColors.secondary[100],
    dividerColor: null,
    focusColor: null,
    highlightColor: null,
    hintColor: null,
    hoverColor: null,
    primaryColor: null,
    primaryColorDark: null,
    primaryColorLight: null,
    primarySwatch: null,
    scaffoldBackgroundColor: AppColors.whiteSwatch,
    secondaryHeaderColor: null,
    shadowColor: null,
    splashColor: null,
    unselectedWidgetColor: null,
    fontFamily: GoogleFonts.albertSans().fontFamily,
    fontFamilyFallback: null,
    iconTheme: null,
    primaryIconTheme: null,
    primaryTextTheme: null,
    textTheme: GoogleFonts.interTextTheme(
      const TextTheme(
        displayLarge: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w800,
        ),
        bodyLarge: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w500,
        ),
        bodyMedium: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w300,
        ),
        labelLarge: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w700,
        ),
        labelMedium: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w600,
        ),
        labelSmall: TextStyle(
          color: AppColors.textPrimary,
          fontWeight: FontWeight.w500,
        ),
      ),
    ),
    typography: Typography.material2021(),
    actionIconTheme: null,
    appBarTheme: AppBarTheme(
      backgroundColor: AppColors.whiteSwatch,
      foregroundColor: AppColors.textPrimary,
      elevation: 0,
      scrolledUnderElevation: null,
      shadowColor: AppColors.primaryDefault,
      surfaceTintColor: AppColors.whiteSwatch,
      shape: null,
      iconTheme: const IconThemeData(
        color: AppColors.primaryDefault,
      ),
      actionsIconTheme: const IconThemeData(
        color: AppColors.primaryDefault,
      ),
      centerTitle: true,
      titleSpacing: NavigationToolbar.kMiddleSpacing,
      toolbarHeight: kToolbarHeight,
      toolbarTextStyle: null,
      titleTextStyle: null,
      systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(
        statusBarColor: AppColors.whiteSwatch,
        statusBarIconBrightness: Brightness.dark,
      ),
    ),
    badgeTheme: null,
    bannerTheme: null,
    bottomAppBarTheme: null,
    bottomNavigationBarTheme: null,
    bottomSheetTheme: null,
    buttonTheme: ButtonThemeData(
      textTheme: AppButtonThemeData.textTheme,
      minWidth: AppButtonThemeData.minWidth,
      height: AppButtonThemeData.height,
      padding: AppButtonThemeData.padding,
      shape: AppButtonThemeData.shape,
      layoutBehavior: AppButtonThemeData.layoutBehavior,
      alignedDropdown: AppButtonThemeData.alignedDropdown,
      buttonColor: AppButtonThemeData.buttonColor,
      disabledColor: AppButtonThemeData.disabledColor,
      focusColor: AppButtonThemeData.focusColor,
      hoverColor: AppButtonThemeData.hoverColor,
      highlightColor: AppButtonThemeData.highlightColor,
      splashColor: AppButtonThemeData.splashColor,
      colorScheme: AppButtonThemeData.colorScheme,
      materialTapTargetSize: AppButtonThemeData.materialTapTargetSize,
    ),
    cardTheme: null,
    checkboxTheme: CheckboxThemeData(
      mouseCursor: AppCheckboxThemeData.mouseCursor,
      fillColor: AppCheckboxThemeData.fillColor,
      checkColor: AppCheckboxThemeData.checkColor,
      overlayColor: AppCheckboxThemeData.overlayColor,
      splashRadius: AppCheckboxThemeData.splashRadius,
      materialTapTargetSize: AppCheckboxThemeData.materialTapTargetSize,
      visualDensity: AppCheckboxThemeData.visualDensity,
      shape: AppCheckboxThemeData.shape,
      side: AppCheckboxThemeData.side,
    ),
    chipTheme: null,
    dataTableTheme: null,
    datePickerTheme: null,
    dialogTheme: null,
    dividerTheme: null,
    drawerTheme: null,
    dropdownMenuTheme: DropdownMenuThemeData(
      textStyle: AppDropdownMenuThemeData.textStyle,
      inputDecorationTheme: AppDropdownMenuThemeData.inputDecorationTheme,
      menuStyle: AppDropdownMenuThemeData.menuStyle,
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ButtonStyle(
        textStyle: AppElevatedButtonStyle.textStyle,
        foregroundColor: AppElevatedButtonStyle.foregroundColor,
        backgroundColor: AppElevatedButtonStyle.backgroundColor,
        overlayColor: AppElevatedButtonStyle.overlayColor,
        shadowColor: AppElevatedButtonStyle.shadowColor,
        surfaceTintColor: AppElevatedButtonStyle.surfaceTintColor,
        elevation: AppElevatedButtonStyle.elevation,
        padding: AppElevatedButtonStyle.padding,
        // minimumSize: AppElevatedButtonStyle.minimumSize,
        fixedSize: AppElevatedButtonStyle.fixedSize,
        // maximumSize: AppElevatedButtonStyle.maximumSize,
        iconColor: AppElevatedButtonStyle.iconColor,
        iconSize: AppElevatedButtonStyle.iconSize,
        side: AppElevatedButtonStyle.side,
        shape: AppElevatedButtonStyle.shape,
        mouseCursor: AppElevatedButtonStyle.mouseCursor,
        visualDensity: AppElevatedButtonStyle.visualDensity,
        tapTargetSize: AppElevatedButtonStyle.tapTargetSize,
        animationDuration: AppElevatedButtonStyle.animationDuration,
        enableFeedback: AppElevatedButtonStyle.enableFeedback,
        alignment: AppElevatedButtonStyle.alignment,
        splashFactory: AppElevatedButtonStyle.splashFactory,
      ),
    ),
    expansionTileTheme: null,
    floatingActionButtonTheme: null,
    iconButtonTheme: null,
    listTileTheme: null,
    menuBarTheme: null,
    menuButtonTheme: null,
    menuTheme: null,
    navigationBarTheme: null,
    navigationDrawerTheme: null,
    navigationRailTheme: null,
    outlinedButtonTheme: null,
    popupMenuTheme: null,
    progressIndicatorTheme: null,
    radioTheme: RadioThemeData(
      mouseCursor: AppRadioThemeData.mouseCursor,
      fillColor: AppRadioThemeData.fillColor,
      overlayColor: AppRadioThemeData.overlayColor,
      splashRadius: AppRadioThemeData.splashRadius,
      materialTapTargetSize: AppRadioThemeData.materialTapTargetSize,
      visualDensity: AppRadioThemeData.visualDensity,
    ),
    searchBarTheme: null,
    searchViewTheme: null,
    segmentedButtonTheme: null,
    sliderTheme: null,
    snackBarTheme: null,
    switchTheme: null,
    tabBarTheme: TabBarThemeData(
      indicator: AppTabBarTheme.indicator,
      indicatorColor: AppTabBarTheme.indicatorColor,
      indicatorSize: AppTabBarTheme.indicatorSize,
      dividerColor: AppTabBarTheme.dividerColor,
      dividerHeight: AppTabBarTheme.dividerHeight,
      labelColor: AppTabBarTheme.labelColor,
      labelPadding: AppTabBarTheme.labelPadding,
      labelStyle: AppTabBarTheme.labelStyle,
      unselectedLabelColor: AppTabBarTheme.unselectedLabelColor,
      unselectedLabelStyle: AppTabBarTheme.unselectedLabelStyle,
      overlayColor: AppTabBarTheme.overlayColor,
      splashFactory: AppTabBarTheme.splashFactory,
      mouseCursor: AppTabBarTheme.mouseCursor,
      tabAlignment: AppTabBarTheme.tabAlignment,
    ),
    textButtonTheme: TextButtonThemeData(
      style: ButtonStyle(
        textStyle: AppTextButtonStyle.textStyle,
        foregroundColor: AppTextButtonStyle.foregroundColor,
        backgroundColor: AppTextButtonStyle.backgroundColor,
        overlayColor: AppTextButtonStyle.overlayColor,
        shadowColor: AppTextButtonStyle.shadowColor,
        surfaceTintColor: AppTextButtonStyle.surfaceTintColor,
        elevation: AppTextButtonStyle.elevation,
        padding: AppTextButtonStyle.padding,
        minimumSize: AppTextButtonStyle.minimumSize,
        fixedSize: AppTextButtonStyle.fixedSize,
        maximumSize: AppTextButtonStyle.maximumSize,
        iconColor: AppTextButtonStyle.iconColor,
        iconSize: AppTextButtonStyle.iconSize,
        side: AppTextButtonStyle.side,
        shape: AppTextButtonStyle.shape,
        mouseCursor: AppTextButtonStyle.mouseCursor,
        visualDensity: AppTextButtonStyle.visualDensity,
        tapTargetSize: AppTextButtonStyle.tapTargetSize,
        animationDuration: AppTextButtonStyle.animationDuration,
        enableFeedback: AppTextButtonStyle.enableFeedback,
        alignment: AppTextButtonStyle.alignment,
        splashFactory: AppTextButtonStyle.splashFactory,
      ),
    ),
    textSelectionTheme: TextSelectionThemeData(
      cursorColor: AppColors.primary,
      selectionColor: AppColors.primary[50],
      selectionHandleColor: AppColors.secondary[50],
    ),
    timePickerTheme: null,
    toggleButtonsTheme: null,
    tooltipTheme: null,
  );
}
